language: cpp

addons:
  artifacts: true

env:
  global:
   - secure: "lm3K4g1EhB+vUzg3sj+XO6rENj7H3n8IxwDnAVi2Xd2H/J9tfPxbupdZr4o8duaXtOKOVl623KF+EhC8VRDUmWNXw4yQO1ty91kog7tOd2LRytExv6l8wj2PD6KHgMdgWNTyzYj8OynCv39fepKitSw5euRJk6eiVn+a72FCyErddZUtDyrnH+nFOSmKPULoX+qNYOhuAuIiGrksr0VbL4aDiV0AQeRr6sS0fyzqdDM+KhE8bcCMtBAWh+4uF8MVgxOTXuaZs5x8ebVJfxnOP8qR6QfHDqP0BSUOYHObqwUBUQOReD+m6RcLa+Y/O0tw8NhhiUg/3IP39ospSkIOwbPU9nTIy2w7sgtyGv8+Tc19XJ77Nn00IAPcN+Tq3Ltk++d7FEeyR4unSY9m8bOaxtOSI9cC1FT0SqkmfoP0q9ED34wq+0NAOl1jwddX+3PNC0hzeXuBOaxdC2H1JWdPmp87iRvAHAD0zO3Jkvw9ag53Pa7wlaOFb2RsAM16iVB1XPJCC0bXs6cW64NXWjsjP/8sbxy05K7vzz24c48kPrZp65MJV4AnyT/F09ttXXJnylCyTiZKeTxs9wEVWokXFZDOh6p6b4H/Vqktn6bfhDNJCnJQRiS1we5ni3lqf3Ih9Nbqa1j+51KTq80PwIzwbO6B7uCXIVxiKxw8dw/vg4M="

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode10.2
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release

    deploy:
      provider: s3
      access_key_id: "AKIAJW66HNZFZ6F5GNAQ"
      secret_access_key: "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"
      bucket: "xqdd"
      file: "build/*/*.zip"	
      file_glob: true
      skip_cleanup: true

  - os: osx
    name: "Analyze Clang"
    osx_image: xcode11
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme WhateverGreen -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme WhateverGreen -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
